sudo: required
language: node_js
cache: npm
node_js:
- '8'
before_install:
- npm install -g npm
- npm install promise
before_script:
- npm install
script:
- npm set apikey=$API_KEY && npm run prod
- npm set apikey=$API_KEY && npm test
